name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    name: 'Node.js v${{ matrix.node }}'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 16
          - 18
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '${{ matrix.node }}'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run All Node.js Tests
        run: npm run test
